### ISSUE TITLE
Stuck on Loading...

### ISSUE THREAD

**Issue by swvalenti194** [mcl8on/MMM-PGA#2]
Module just displays loading…this is the error in the logs can’t define “athlete” Any ideas??

`1|MagicMirror  | MMM-PGA retrieving Tournament Data
1|MagicMirror  | [2020-11-26 08:48:24.936] [ERROR]
1|MagicMirror  | Whoops! There was an uncaught exception...
1|MagicMirror  | [2020-11-26 08:48:24.937] [ERROR]
1|MagicMirror  | TypeError: Cannot read property 'athlete' of undefined
1|MagicMirror  |     at Request._callback (/home/pi/MagicMirror/modules/MMM-PGA/ESPN.js:49:65)
1|MagicMirror  |     at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
1|MagicMirror  |     at Request.emit (events.js:200:13)
1|MagicMirror  |     at Request. (/home/pi/MagicMirror/node_modules/request/request.js:1154:10)
1|MagicMirror  |     at Request.emit (events.js:200:13)
1|MagicMirror  |     at IncomingMessage. (/home/pi/MagicMirror/node_modules/request/request.js:1076:12)
1|MagicMirror  |     at Object.onceWrapper (events.js:288:20)
1|MagicMirror  |     at IncomingMessage.emit (events.js:205:15)
1|MagicMirror  |     at endReadableNT (_stream_readable.js:1154:12)
1|MagicMirror  |     at processTicksAndRejections (internal/process/task_queues.js:84:9)`

**Comment by swvalenti194** [comment]
Forked and fixed
